# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_cache.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kv_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_cache.proto\x12\x07kvcache\"G\n\x10InferenceRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x10\n\x08kv_cache\x18\x02 \x01(\x0c\x12\x12\n\nprompt_len\x18\x03 \x01(\x05\"(\n\x11InferenceResponse\x12\x13\n\x0b\x66irst_token\x18\x01 \x01(\t2V\n\x0eKVCacheService\x12\x44\n\tInference\x12\x19.kvcache.InferenceRequest\x1a\x1a.kvcache.InferenceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=27
  _globals['_INFERENCEREQUEST']._serialized_end=98
  _globals['_INFERENCERESPONSE']._serialized_start=100
  _globals['_INFERENCERESPONSE']._serialized_end=140
  _globals['_KVCACHESERVICE']._serialized_start=142
  _globals['_KVCACHESERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
